version: '3.8'
services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak-container
    environment:
      KC_DB: dev-mem
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - '8901:8080'
